### ISSUE TITLE
human rating of algorithm results using ELO

### ISSUE THREAD

**Issue by stebo85** [QSMxT/QSM-CI#1]
We could generate an ELO based ranking of QSM reconstruction results in addition to computational metrics

**Comment by astewartau** [comment]
Sounds great! I've implemented this for a personal project before too. 😁

**Comment by stebo85** [comment]
Oh, cool :p love it! I have never seen it in papers for manual ratings of images 😁

**Comment by astewartau** [comment]
This is being added to a separate project
